### ISSUE TITLE
申请

### ISSUE THREAD

**Issue by AH-dark** [HMUniversity/About#422]
家里蹲大学：  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;您好！我志愿加入家里蹲大学躺平！

如果你想加入一个特定学院请在此处勾选：
- [x] [St. Linus College](https://github.com/orgs/HMUniversity/teams/st-linus-college)
- [ ] [St. Chi College](https://github.com/orgs/HMUniversity/teams/st-chi-college)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;此致  
敬礼  
AHdark

**Comment by Cubik65536** [comment]
Dear AH-dark,

The admission committee has concluded its evaluation of Early Decision applicants to Home University. Unfortunately, we are unable to offer you a place in our class. Since Home University was your top choice, we understand this news is very disappointing.

The admission committee appreciates the time and effort you put into applying to Home University. We wish you every success as you pursue your education.

Sincerely,
_**Cubik65536**_
Deputy Vice-Chancellor, Home University
